# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_auto_20190325_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='somestring', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='somestring', max_length=255),
        ),
    ]
