# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_auto_20190325_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
