# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_race_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='workers',
            field=models.ManyToManyField(related_name='events', to='races.User'),
        ),
    ]
